baseURL = 'https://keocheung.github.io/blog/'
languageCode = 'zh-Hans'
title = "Keo Cheung's Blog"
theme = 'paper'

[params]

github = 'keocheung'
twitter = 'Keo1248'
mastodon = 'https://elk.zone/mona.do/@keo'
rss = true